title: Melon Status

buildFuture: true

languageCode: en

defaultContentLanguage: en

baseURL: https://status.melonbot.io

enableGitInfo: true

params:

  categories:
    - name: MELON
      description: The main servers are located here.
      closed: false

  systems:
    - name: Website
      category: MELON
      description: The main website for Melon.
      link: https://melonbot.io/
    - name: Documentation
      category: MELON
      description: The documentation website for Melon.
      link: https://guide.melonbot.io/

  dateFormat: January 2, 2006 at 3:04 PM UTC
  shortDateFormat: 15:04 UTC — Jan 2

  useRelativeTime: true

  skipSeconds: false

  enableLastMod: true

  useLargeHeaderDesign: false

  incidentHistoryFormat: "yearly"

  disableIncidentHistory: false

  disableDarkMode: false

  useLogo: true

  logo: logo.svg

  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.

  disableComplexCalculations: false

  incidentPostsPerPage: 10

  brand: "#0a0c0f"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"

  alwaysKeepBrandColor: true

  headerTextColor: white

  googleAnalytics: UA-00000000-1

theme: cstate

preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
